{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "hw3-chart.fullname" . }}
  labels:
    {{- include "hw3-chart.labels" . | nindent 4 }}
spec:
  jobLabel: {{ include "hw3-chart.fullname" . }}
  namespaceSelector:
    matchNames:
    - "{{ $.Release.Namespace }}"
  selector:
    matchLabels:
      {{- include "hw3-chart.selectorLabels" . | nindent 6 }}
  endpoints:
  - interval: {{ .Values.metrics.interval }}
    port: {{ .Values.metrics.port }}
    path: {{ .Values.metrics.path }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "{{ .Release.Name }}-service-monitor-pg"
  labels:
    tier: app
    release: "{{ .Release.Name }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-postgresql"
  endpoints:
  - port: metrics
    interval: 10s
{{- end }}