apiVersion: getambassador.io/v2
kind: FilterPolicy
metadata:
  name: "myapp-filter-policy"
spec:
  rules:
    - host: "*"
      path: "/users/profile"
      filters:
        - name: "myapp-jwt-filter"