apiVersion: getambassador.io/v2
kind: Filter
metadata:
  name: "myapp-jwt-filter"
spec:
  JWT:
    jwksURI: "http://auth-app-auth-app-chart:8000/.well-known/jwks.json"
    insecureTLS: true
    renegotiateTLS: freelyAsClient
    validAlgorithms:
      - "RS256"
    requireAudience: false
    requireIssuer: false
    requireIssuedAt: false
    requireExpiresAt: false
    requireNotBefore: false
    injectRequestHeaders:
      - name: "X-Token-String"
        value: "{{ .token.Raw }}"
      - name: "X-User-Id"
        value: "{{ .token.Claims.sub }}"
      - name: "X-Phone"
        value: "{{ .token.Claims.phone }}"
      - name: "X-First-Name"
        value: "{{ .token.Claims.first_name }}"
      - name: "X-Last-Name"
        value: "{{ .token.Claims.last_name }}"