apiVersion: apps/v1
kind: Deployment
metadata:
  name: otus-hw2-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: otus-hw2-app
  template:
    metadata:
      labels:
        app: otus-hw2-app
    spec:
      containers:
        - name: otus-hw2
          image: sabirov/otus-hw2:v1
          env:
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DATABASE_URI
            - name: GREETING
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: GREETING
          ports:
            - name: web
              containerPort: 80