apiVersion: v1
kind: Secret
metadata:
  name: {{ include "store-app-chart.fullname" . }}-secret
type: Opaque
data:
  ENV: {{ .Values.app.env | b64enc | quote }}
  BROKER: {{ .Values.broker.url | b64enc | quote }}
  DB_PASSWORD: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
  DB_USERNAME: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  DB_DATABASE: {{ .Values.postgresql.postgresqlDatabase | b64enc | quote }}
  DB_HOST: {{ (include "postgresql.fullname" .) | b64enc | quote }}
  DB_PORT: {{ .Values.postgresql.service.port | b64enc | quote }}
  DB_DRIVERNAME: {{ .Values.app.dbDriver | b64enc | quote }}