apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-app-chart.fullname" . }}-secret
type: Opaque
data:
  ENV: {{ .Values.app.env | b64enc | quote }}
  DB_PASSWORD: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
  DB_USERNAME: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  DB_DATABASE: {{ .Values.postgresql.postgresqlDatabase | b64enc | quote }}
  DB_HOST: {{ (include "postgresql.fullname" .) | b64enc | quote }}
  DB_PORT: {{ .Values.postgresql.service.port | b64enc | quote }}
  DB_DRIVERNAME: {{ .Values.app.dbDriver | b64enc | quote }}
  SECURITY_PASSWORD_SALT: {{ .Values.app.securityPasswordSalt | b64enc | quote  }}
  PRIVATE_KEY: {{ .Values.jwt.privateKey | b64enc | quote }}
  PUBLIC_KEY: {{ .Values.jwt.publicKey | b64enc | quote }}