{
 "title": "CPU usage",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "CPU usage namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\"}[5m])) by (namespace)",
     "legendFormat": "NS {{namespace}}"
    }
   ]
  },
  {
   "title": "Memory usage namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\"}) by (namespace)",
     "legendFormat": "NS {{namespace}}"
    }
   ]
  },
  {
   "title": "CPU usage pods app",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", pod=~\"myapp-hw3-chart.*\"}[5m])) by (pod)",
     "legendFormat": "pod {{pod}}"
    }
   ]
  },
  {
   "title": "Memory usage pods app",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{image!=\"\", pod=~\"myapp-hw3-chart.*\"}[5m])) by (pod)",
     "legendFormat": "pod {{pod}}"
    }
   ]
  }
 ]
}