{
 "title": "Postgres",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_xact_commit[5m]))",
     "legendFormat": "Commits"
    },
    {
     "expr": "sum(irate(pg_stat_database_xact_rollback[5m]))",
     "legendFormat": "Rollback"
    }
   ]
  },
  {
   "title": "Conflicts/Deadlocks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_deadlocks[5m]))",
     "legendFormat": "Deadlocks"
    },
    {
     "expr": "sum(irate(pg_stat_database_conflicts[5m]))",
     "legendFormat": "Conflicts"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pg_stat_database_blks_hit) by (datname) /\n(sum(pg_stat_database_blks_hit) by (datname) + \nsum(pg_stat_database_blks_read) by (datname))",
     "legendFormat": "Cache hit rate {{datname}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(max_over_time(pg_stat_activity_count[$interval]) or\nmax_over_time(pg_stat_activity_count[5m])) by (state)",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "sum(max_over_time(pg_stat_activity_count[$interval]) or\nmax_over_time(pg_stat_activity_count[5m]))",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}